name: pinano # you probably want to 'snapcraft register <name>'
version: '2.8.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: GNU nano text editor
description: |
  This is the GNU nano text editor version 2.8.4 packed as a snap for raspberry PI. The source code for this snap can be found at https://github.com/VBota1/pinano. All credits go to the GNU nano developers https://www.nano-editor.org/who.php To get writing access connect to the follwoing plugs: sudo snap connect pinano:home core:home | sudo snap connect pinano:raw-usb core:raw-usb | sudo snap connect pinano:removable-media core:removable-media

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  pinano:
    source: /home/vbota/workspace/nano/nano-2.8.4
    plugin: autotools

apps:
  pinano:
    command: bin/nano
    plugs: [home, raw-usb, removable-media]
